language: node_js
node_js:
  - '12'

install:
  - npm ci
env:
  - CI=true

script:
  - npm test
  - npm run test:coverage

before_deploy:
  - npm install netlify-cli -g
  - npm run build
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./build
  skip_cleanup: true
  on:
    branch: master