language: node_js
node_js:
  - '12'

install:
  - npm ci

script:
  - npm test
  - npm run test:coverage

before_deploy:
  - npm install netlify-cli -g
  - npm run build
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: master